spring:
  application:
    name: auth-service

  boot:
    admin:
      client:
        enabled: true
        instance:
          name: Auth Service
          service-url: http://localhost:8086
        url: http://localhost:8081
        auto-registration: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/authdb

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.servlet: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
      enable:
        include: health

server:
  port: 8086

jwt:
  secret: bXktc3VwZXItc2VjcmV0LWtleS0yNThbrurgnwrgjnjngnfndmfddY=
  expiration: 86400000