spring:
  application:
    name: patient-service

  boot:
    admin:
      client:
        enabled: true
        instance:
          name: Patient Service
          service-url: http://localhost:8082
          management-url: http://localhost:8082/actuator
          health-url: http://localhost:8082/actuator/health
        url: http://localhost:8080   # Admin server
        auto-registration: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/patientdb

logging:
  level:
    org:
      springframework:
        web: DEBUG
        servlet: DEBUG
    de.codecentric.boot.admin.client: DEBUG   # enable admin client logs

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8082
