app:
  environment: prod

spring:
  application:
    name: appointment-service

  boot:
    admin:
      client:
        enabled: true
        instance:
          name: Appointment Service
          service-url: http://localhost:8084
        url: http://localhost:8080
        auto-registration: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/appointmentdb

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    topic:
      name: ${KAFKA_TOPIC:appointment-events}

logging:
  level:
    org:
      springframework:
        web: DEBUG
        servlet: DEBUG
      apache:
        kafka:
          clients:
            producer: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
      enable:
        include: health

server:
  port: 8084

doctor:
  service:
    url: http://doctor-service:8083/api/v1/doctor
    data:
      mongodb:
        uri: mongodb://localhost:27017/doctordb

patient:
  service:
    url: http://patient-service:8082/api/v1/patient
  data:
    mongodb:
      uri:mongodb://localhost:27017/patientdb
